import { agents, directTool, skills, tools } from "@routecraft/ai";
import {
  type CraftConfig,
  type Principal,
  defineConfig,
  timingSafeStringEqual,
} from "@routecraft/routecraft";
import { EDITOR_AGENT } from "./shared/defaults.js";
import { env, mailConfigured, modelId } from "./env.js";

/**
 * What the folder convention cannot work out on its own.
 *
 * `craft start` discovers the capabilities, the agents and the house skills
 * from disk, so none of them is listed here. What is listed is everything
 * that needs a decision: who may reach this instance, which listeners exist,
 * which model provider is in use, and what an agent may call.
 *
 * The rule for adding something here is that discovery could not have known
 * it. A capability belongs in `capabilities/`; a prompt belongs in
 * `agents/`; whether a route should be running at all belongs on the route,
 * as `.enabled()`.
 */

/**
 * One key, one validator, every surface.
 *
 * This is the static-key rung of the credential ladder, pre-applied: the
 * approval endpoint, the MCP transport, the editor door and the ops door all
 * verify the same `CRAFT_API_KEY`, generated by `bun run setup` and living
 * only in `.env`.
 * Nothing here mints or stores a credential. Routecraft verifies; issuers
 * issue, and at this rung the issuer is the setup script that made the
 * bytes.
 *
 * The comparison MUST be `timingSafeStringEqual`. `===` returns as soon as
 * two bytes differ, and that timing is measurable across a network, which
 * turns a 256-bit secret into a byte-at-a-time guess.
 *
 * Moving up the ladder is a change to this one object: `jwt({ secret, issuer,
 * audience })` for tokens you mint yourself, `jwks({ jwksUrl, issuer,
 * audience })` for a real identity provider. Every surface follows, and no
 * route changes, because a route says what it needs (`.authorize()`) and
 * never how a credential is checked.
 */
/**
 * The subject every principal minted from `CRAFT_API_KEY` carries.
 *
 * Exported because the approvals hook has to recognise it: the operator
 * holding the instance's own key is the one caller who would otherwise
 * authenticate successfully and then be refused as an unknown approver.
 */
export const OPERATOR_SUBJECT = "operator";

const apiKeyAuth = {
  validator: (token: string): Principal => {
    if (!timingSafeStringEqual(env.CRAFT_API_KEY, token)) {
      throw new Error("unknown token");
    }
    return {
      kind: "custom",
      scheme: "bearer",
      subject: OPERATOR_SUBJECT,
      scopes: ["ops:introspection", "ops:dispatch"],
    };
  },
};

/**
 * The tools aria may call, declared once and unconditionally.
 *
 * Enablement does the filtering. A capability whose `.enabled()` predicate
 * is false is absent from the catalogue this builder is handed, so a
 * dormant mail route simply is not offered to the model: "the agent cannot
 * send mail until a mailbox is configured" is true by construction rather
 * than by anyone remembering to edit this list.
 *
 * The builder form rather than a plain array, and that is not a style
 * choice: a plain `tools([...])` array resolves every name it holds at each
 * dispatch and throws `RC5003` for one that is not in the catalogue, so a
 * statically listed disabled route would fail every agent turn. Filtering
 * against the catalogue is what turns "not available" into "not offered".
 *
 * `Bash` is an alias: the fn registry maps that familiar name onto the
 * `bash-runner` capability, so the model sees a name it knows while the
 * thing it reaches is an ordinary route in this repository.
 */
export const ARIA_TOOLS = [
  "Bash",
  "Direct(web-search)",
  "Direct(web-fetch)",
  "Direct(workspace-read)",
  "Direct(workspace-write)",
  "Direct(workspace-list)",
  "Direct(memory-save)",
  "Direct(memory-recall)",
  "Direct(schedule-task)",
  "Direct(list-schedules)",
  "Direct(cancel-schedule)",
  "Direct(request-approval)",
  "Direct(compact)",
  "Direct(mail-reply)",
];

/**
 * The wanted list, narrowed to what this context actually offers.
 *
 * Exported so a test can resolve it against a context and assert that a
 * dormant capability is not on the agent's surface. `craft start` reads only
 * `craftConfig`; the extra export costs nothing and buys the guarantee a
 * comment cannot.
 */
export const ariaTools = tools((catalog) => {
  const offered = new Set([
    ...catalog.fns.map((fn) => fn.name),
    ...catalog.routes.map((route) => `Direct(${route.id})`),
  ]);
  return ARIA_TOOLS.filter((name) => offered.has(name));
});

export const craftConfig: CraftConfig = defineConfig({
  name: "craft-harness",

  /**
   * Four listeners, deliberately not one. The approval door is opened by
   * whoever was mailed a link; the MCP transport is where an assistant
   * connects; the editor door is where a person's IDE connects; the ops
   * surface answers `craft exec` and `craft ops` and has no business being
   * on any of the other three. All four verify the same key.
   *
   * A port per purpose is what lets a firewall rule say "the editor, not
   * management" without a proxy in front of it, and it is why the MCP
   * transport did not simply gain a second protocol.
   */
  servers: {
    approvals: { host: "localhost", port: env.HTTP_PORT, auth: apiKeyAuth },
    mcp: { host: "localhost", port: env.MCP_PORT, auth: apiKeyAuth },
    // `127.0.0.1` rather than `localhost`, and that is not a style choice.
    // `localhost` resolves through the host's own rules, so on a machine
    // that answers it with `::1` first the listener binds IPv6 while
    // `bun run setup` writes `http://127.0.0.1:` into the editor profile and
    // HELP.md prints the same. The editor would then dial an address nothing
    // is listening on. The three servers above predate this and are left
    // alone; they carry the same latent ambiguity and no caller has hit it.
    editor: { host: "127.0.0.1", port: env.ACP_PORT, auth: apiKeyAuth },
    ops: { host: "localhost", port: env.OPS_PORT, auth: apiKeyAuth },
  },

  http: {
    mounts: {
      /**
       * The one deliberately public surface, and the exception worth
       * stating: an approver clicks a link from their mail client and has
       * no API key. Their credential is the single-use token in the URL.
       *
       * `auth: false` removes the wall, it does not remove the validator:
       * the server's validator stays reachable, so a route here that
       * declares `.authorize()` still pulls verification through it. Adding
       * a walled route to this surface is therefore a route-level decision,
       * not a config change.
       */
      approvals: { path: "/", server: "approvals", auth: false },
    },
  },

  ops: {
    server: "ops",
    /**
     * Every management tier is off unless named here, and each names the
     * scope its caller must carry. `true` would mean "no credential
     * demanded", which was right while nothing was walled and is wrong now
     * that something is: a refused caller is told which scope it lacks, and
     * `craft exec` reads that off the challenge.
     */
    tiers: { introspection: "ops:introspection", dispatch: "ops:dispatch" },
  },

  suspension: {
    // Parked approvals must outlive a restart, which is the entire point of
    // parking them. The default store is SQLite where a driver is available.
    secret: env.ROUTECRAFT_SUSPENSION_SECRET,
  },

  llm: {
    providers: { [env.LLM_PROVIDER]: { apiKey: env.LLM_API_KEY } },
  },

  agent: {
    agents: await agents("./agents", {
      aria: {
        tools: ariaTools,
        blocks: await skills({ source: "./skills" }),
      },
    }),
    functions: {
      Bash: directTool("bash-runner"),
    },
    defaultOptions: { model: modelId },
    /**
     * An allowlist over the whole tool surface. Every kind must be decided,
     * which is what stops a later edit narrowing the surface by accident.
     *
     * `mcp: false` is the load-bearing one: this harness is an MCP SERVER,
     * and a tool discovered from some external MCP client is reach nobody in
     * this repository granted. Wrap one in a capability if the agent needs
     * it; then it is a route with a name, an input schema and a diff.
     */
    toolPolicy: { fn: true, direct: true, mcp: false },
  },

  /**
   * The editor's way in, on from boot and behind the same wall.
   *
   * The first-party key rather than `plugins: [acpPlugin()]`, because the
   * appliers run in a fixed order regardless of the order these keys are
   * written in: `acp` builds one route per agent and therefore has to apply
   * after `agent` registered them, which the plugin-array form makes the
   * author's problem and this form does not.
   *
   * `agent` is named rather than left to the default. That default only
   * resolves for a context holding exactly one agent, and this one holds
   * aria and researcher, so an unset value would refuse `session/new` with
   * a message listing both instead of answering as Aria.
   */
  acp: {
    server: "editor",
    agent: EDITOR_AGENT,
    agentInfo: {
      name: "craft-harness",
      title: "Craft Harness",
      version: "0.1.0",
    },
  },

  mcp: {
    name: "craft-harness",
    title: "Craft Harness",
    version: "0.1.0",
    transport: "http",
    server: "mcp",
    // The resource identifier clients verify against (RFC 9728). Required
    // for the HTTP transport outside development, and it has to be the
    // address a client actually reaches rather than this process's port.
    resource: { url: env.MCP_URL },
  },

  /**
   * Declared only when there is a mailbox to declare. The mail capabilities
   * are `.enabled()` on the same predicate, so with no credentials they are
   * registered, off, and reported by `/ops` with the variables to set;
   * declaring an account with nothing behind it would add a second way to
   * be half-configured.
   */
  ...(mailConfigured
    ? {
        mail: {
          accounts: {
            default: {
              imap: {
                host: env.MAIL_IMAP_HOST,
                auth: { user: env.MAIL_ADDRESS, pass: env.MAIL_APP_PASSWORD },
              },
              smtp: {
                host: env.MAIL_SMTP_HOST,
                port: env.MAIL_SMTP_PORT,
                secure: false,
                requireTLS: true,
                auth: { user: env.MAIL_ADDRESS, pass: env.MAIL_APP_PASSWORD },
                from: env.MAIL_ADDRESS,
              },
            },
          },
          folder: env.MAIL_FOLDER,
        },
      }
    : {}),
});
