/**
 * Generate this project's own credentials, once.
 *
 * Two secrets have no sensible default and cannot be committed: the API key
 * that secures every surface the harness exposes, and the secret the
 * suspension store signs resume links with. This script generates both and
 * writes them where they are read from: `.env` for the process, and
 * `.routecraft/settings.yaml` for the CLI, so `craft exec` works with no
 * flags immediately.
 *
 * It runs from `bun run setup`, not from install and not from boot. A
 * framework that generated a credential the first time an app started would
 * be minting, and a harness that minted on install would put a secret on
 * disk before anyone had decided to run it. This is one explicit command,
 * and it says what it wrote.
 *
 * Idempotent in the way that matters: an existing value is never replaced.
 * Run it after a fresh clone (which has neither file) and it fills both in;
 * run it again and it only fills what is missing. Rotating is deleting the
 * lines and running it again, which is a thing you can mean rather than a
 * thing that happens to you.
 */

import { randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const ENV_FILE = join(ROOT, ".env");
const SETTINGS_FILE = join(ROOT, ".routecraft", "settings.yaml");

/**
 * 32 bytes of randomness, URL-safe.
 *
 * Base64url rather than hex so the key stays short enough to paste, and
 * without `+`, `/` or `=`, which would need quoting in a YAML scalar and a
 * shell argument. 32 bytes is 256 bits: a bearer credential on a listening
 * port is guessed offline, so the length is the whole defence.
 */
function generateSecret(): string {
  return randomBytes(32).toString("base64url");
}

/** Values already present in `.env`, by name. */
function parseEnvFile(contents: string): Map<string, string> {
  const values = new Map<string, string>();
  for (const line of contents.split("\n")) {
    const match = /^\s*([A-Z][A-Z0-9_]*)\s*=(.*)$/.exec(line);
    if (match) values.set(match[1]!, match[2]!.trim());
  }
  return values;
}

/** The variables setup owns, and how to produce one when it is missing. */
const GENERATED = [
  {
    name: "CRAFT_API_KEY",
    note: "secures the approval endpoint, the MCP transport and the ops door",
  },
  {
    name: "ROUTECRAFT_SUSPENSION_SECRET",
    note: "signs the single-use links that resolve an approval",
  },
] as const;

/**
 * Variables a person must supply. Written as empty lines with a comment so
 * `.env` shows what is still missing, rather than being silently absent and
 * failing at boot with no hint of where the value belongs.
 */
const REQUIRED_BY_HAND = [
  { name: "LLM_API_KEY", note: "your model provider's key" },
] as const;

async function main(): Promise<void> {
  const existing = existsSync(ENV_FILE)
    ? parseEnvFile(await readFile(ENV_FILE, "utf8"))
    : new Map<string, string>();

  const generated: string[] = [];
  const blanked: string[] = [];
  const lines: string[] = [];

  if (!existing.has("NODE_ENV")) {
    lines.push(
      "# Development mode: the MCP transport requires an HTTPS MCP_URL outside it.",
      "NODE_ENV=development",
      "",
    );
  }

  for (const { name, note } of GENERATED) {
    // A present-but-empty value is what deleting a key by blanking it leaves
    // behind. Refilling the line in place is what keeps a rotation from
    // appending a second declaration of the same variable.
    if (existing.get(name)) continue;
    if (existing.has(name)) {
      blanked.push(name);
      continue;
    }
    lines.push(
      `# Generated by bun run setup: ${note}.`,
      `${name}=${generateSecret()}`,
      "",
    );
    generated.push(name);
  }

  for (const { name, note } of REQUIRED_BY_HAND) {
    if (existing.has(name)) continue;
    lines.push(`# Set this by hand: ${note}.`, `${name}=`, "");
  }

  let body = existsSync(ENV_FILE) ? await readFile(ENV_FILE, "utf8") : "";
  for (const name of blanked) {
    body = body.replace(
      new RegExp(`^${name}=\\s*$`, "m"),
      `${name}=${generateSecret()}`,
    );
    generated.push(name);
  }
  if (lines.length > 0 || blanked.length > 0) {
    const separator = body === "" || body.endsWith("\n") ? "" : "\n";
    await writeFile(ENV_FILE, body + separator + lines.join("\n"), {
      mode: 0o600,
    });
    // mode applies on creation only, so an existing file needs telling.
    await chmod(ENV_FILE, 0o600);
  }

  // Read back rather than reusing the value in hand: on a second run the key
  // came from the file, and the settings file must carry whatever `.env`
  // actually holds rather than something this run happened to generate.
  const finalEnv = parseEnvFile(await readFile(ENV_FILE, "utf8"));
  const apiKey = finalEnv.get("CRAFT_API_KEY") ?? "";
  const opsPort = finalEnv.get("OPS_PORT") ?? "9090";

  const settings = existsSync(SETTINGS_FILE)
    ? await readFile(SETTINGS_FILE, "utf8")
    : "";
  if (apiKey !== "" && settings.includes(`token: ${apiKey}`)) {
    console.log(`Kept   ${rel(SETTINGS_FILE)} (already matches .env)`);
  } else {
    // Rewritten rather than kept: the documented rotation deletes the token
    // from both files, which leaves this one present but carrying a key that
    // .env no longer has. Keeping it would answer 401 and blame the caller.
    await mkdir(dirname(SETTINGS_FILE), { recursive: true, mode: 0o700 });
    await writeFile(
      SETTINGS_FILE,
      [
        "# Written by bun run setup. Gitignored: it carries a credential.",
        "# `craft exec` and `craft ops` read this, so neither needs a flag.",
        `url: http://127.0.0.1:${opsPort}`,
        `token: ${apiKey}`,
        "",
      ].join("\n"),
      { mode: 0o600 },
    );
    await chmod(SETTINGS_FILE, 0o600);
    console.log(`Wrote  ${rel(SETTINGS_FILE)} (ops url and token)`);
  }

  for (const name of generated) console.log(`Wrote  .env ${name}`);
  for (const { name } of GENERATED) {
    if (!generated.includes(name))
      console.log(`Kept   .env ${name} (already set)`);
  }

  const missing = REQUIRED_BY_HAND.filter(
    ({ name }) => (finalEnv.get(name) ?? "") === "",
  );
  if (missing.length > 0) {
    console.log(
      `\nStill needed, by hand in .env: ${missing.map((m) => m.name).join(", ")}.`,
    );
  }
  console.log("\nThen: bun run dev");
}

function rel(path: string): string {
  return path.slice(ROOT.length + 1);
}

await main();
